### ISSUE TITLE
Parkinson's assesment task fails to go to second page

### ISSUE THREAD

**Issue by LarsRefsgaard** [cph-cachet/cognition_package#19]
I open the task and click next to go to the second page, and I get a null check operator used on a null value with stack trace:
https://github.com/cph-cachet/cognition_package/blob/2aef1b87b498b42f1e4ea549615ce9fb31e86a15/lib/src/ui/ActivityBody/rpui_flanker_activity_body.dart#L120
```
#181    StatefulElement.update
framework.dart:5274
#182    Element.updateChild
framework.dart:3686
#183    ComponentElement.performRebuild
framework.dart:5111
#184    Element.rebuild
framework.dart:4805
#185    ProxyElement.update
framework.dart:5417
#186    Element.updateChild
framework.dart:3686
#187    ComponentElement.performRebuild
framework.dart:5111
#188    StatefulElement.performRebuild
framework.dart:5251
#189    Element.rebuild
framework.dart:4805
#190    StatefulElement.update
framework.dart:5274
#191    Element.updateChild
framework.dart:3686
#192    SingleChildRenderObjectElement.update
framework.dart:6442
#193    Element.updateChild
framework.dart:3686
#194    ComponentElement.performRebuild
framework.dart:5111
#195    Element.rebuild
framework.dart:4805
#196    ProxyElement.update
framework.dart:5417
#197    Element.updateChild
framework.dart:3686
#198    SingleChildRenderObjectElement.update
framework.dart:6442
#199    Element.updateChild
framework.dart:3686
#200    ComponentElement.performRebuild
framework.dart:5111
#201    StatefulElement.performRebuild
framework.dart:5251
#202    Element.rebuild
framework.dart:4805
#203    StatefulElement.update
framework.dart:5274
#204    Element.updateChild
framework.dart:3686
#205    ComponentElement.performRebuild
framework.dart:5111
#206    StatefulElement.performRebuild
framework.dart:5251
#207    Element.rebuild
framework.dart:4805
#208    StatefulElement.update
framework.dart:5274
#209    Element.updateChild
framework.dart:3686
#210    ComponentElement.performRebuild
framework.dart:5111
#211    Element.rebuild
framework.dart:4805
#212    ProxyElement.update
framework.dart:5417
#213    Element.updateChild
framework.dart:3686
#214    ComponentElement.performRebuild
framework.dart:5111
#215    Element.rebuild
framework.dart:4805
#216    ProxyElement.update
framework.dart:5417
#217    Element.updateChild
framework.dart:3686
#218    ComponentElement.performRebuild
framework.dart:5111
#219    Element.rebuild
framework.dart:4805
#220    ProxyElement.update
framework.dart:5417
#221    Element.updateChild
framework.dart:3686
#222    ComponentElement.performRebuild
framework.dart:5111
#223    StatefulElement.performRebuild
framework.dart:5251
#224    Element.rebuild
framework.dart:4805
#225    StatefulElement.update
framework.dart:5274
#226    Element.updateChild
framework.dart:3686
#227    ComponentElement.performRebuild
framework.dart:5111
#228    Element.rebuild
framework.dart:4805
#229    ProxyElement.update
framework.dart:5417
#230    Element.updateChild
framework.dart:3686
#231    ComponentElement.performRebuild
framework.dart:5111
#232    StatefulElement.performRebuild
framework.dart:5251
#233    Element.rebuild
framework.dart:4805
#234    StatefulElement.update
framework.dart:5274
#235    Element.updateChild
framework.dart:3686
#236    ComponentElement.performRebuild
framework.dart:5111
#237    StatefulElement.performRebuild
framework.dart:5251
#238    Element.rebuild
framework.dart:4805
#239    StatefulElement.update
framework.dart:5274
#240    Element.updateChild
framework.dart:3686
#241    ComponentElement.performRebuild
framework.dart:5111
#242    StatefulElement.performRebuild
framework.dart:5251
#243    Element.rebuild
framework.dart:4805
#244    BuildOwner.buildScope
framework.dart:2780
#245    WidgetsBinding.drawFrame
binding.dart:903
#246    RendererBinding._handlePersistentFrameCallback
binding.dart:358
#247    SchedulerBinding._invokeFrameCallback
binding.dart:1284
#248    SchedulerBinding.handleDrawFrame
binding.dart:1214
#249    SchedulerBinding._handleDrawFrame
binding.dart:1072
#250    _invoke (dart:ui/hooks.dart:142:13)
#251    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#252    _drawFrame (dart:ui/hooks.dart:112:31)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was
MaterialApp
carp_study_app.dart:165
════════════════════════════════════════════════════════════════════════════════
```

**Comment by bardram** [comment]
All bang operators (!) have been removed now.
